// ex: src/constants/permissions.ts
export const PERMISSIONS = {
  DEMANDES_READ: "DEMANDES_READ",
  DEMANDES_MANAGE: "DEMANDES_MANAGE",
  DOCUMENTS_READ: "DOCUMENTS_READ",
  DOCUMENTS_VERIFY: "DOCUMENTS_VERIFY",
  ABONNEMENTS_READ: "ABONNEMENTS_READ",
  ABONNEMENTS_MANAGE: "ABONNEMENTS_MANAGE",
  CONTACTS_READ: "CONTACTS_READ",
  CONFIG_MANAGE: "CONFIG_MANAGE",
  DEPARTMENTS_MANAGE: "DEPARTMENTS_MANAGE",
  FILIERES_MANAGE: "FILIERES_MANAGE",
}
