// ex: src/constants/roles.ts
export const ROLE_DEFAULT_PERMS: Record<string, string[]> = {
  ADMIN: [
    "DEMANDES_READ","DEMANDES_MANAGE",
    "DOCUMENTS_READ","DOCUMENTS_VERIFY",
    "ABONNEMENTS_READ","ABONNEMENTS_MANAGE",
    "CONTACTS_READ",
    "CONFIG_MANAGE",
    "DEPARTMENTS_MANAGE","FILIERES_MANAGE",
  ],
  SUPERVISEUR: [
    "DEMANDES_READ",
    "DOCUMENTS_READ","DOCUMENTS_VERIFY",
    "ABONNEMENTS_READ",
    "CONTACTS_READ",
  ],
  INSTITUT: [
    "DEMANDES_READ","DEMANDES_MANAGE",
    "DOCUMENTS_READ",
    "ABONNEMENTS_READ",
  ],
  TRADUCTEUR: [
    "DOCUMENTS_READ","DOCUMENTS_VERIFY",
    "DEMANDES_READ",
  ],
  DEMANDEUR: [
    "DEMANDES_READ",
    "DOCUMENTS_READ",
  ],
}
